services:
  chatbot-integracar:
    build:
      context: .
      dockerfile: prod.Dockerfile
    volumes:
      - app_shared:/code/media
      - static_volume:/code/static
    env_file:
      - ./.env
    command: /start
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
      - proxy

  qcluster:
    build:
      context: .
      dockerfile: prod.Dockerfile
    volumes:
      - app_shared:/code/media
    env_file:
      - ./.env
    command: python manage.py qcluster
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  redeneuralbert:
    image: integracar/redeneuralbert:8.0
    ports:
      - "8001:8000"
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: paradedb/paradedb:latest-pg17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: chatbot-integracar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app-network
    healthcheck:
      test: pg_isready -d chatbot-integracar -U postgres
      interval: 5s
      retries: 10
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

  proxy:
    external: true

volumes:
  app_shared:
  postgres_data:
  static_volume:
