# Generated by Django 5.2.6 on 2025-09-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_usuario_created_at_usuario_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se este usuário deve ser tratado como ativo. Desmarque esta opção ao invés de excluir contas.', verbose_name='ativo'),
        ),
    ]
