server {
    listen 443 ssl;
    server_name chatbotintegracar.online www.chatbotintegracar.online;

    ssl_certificate /etc/letsencrypt/live/chatbotintegracar.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/chatbotintegracar.online/privkey.pem;

    location /static/ {
        alias /code/static/;
    }

    location /media/ {
        alias /code/media/;
    }

    client_max_body_size 50M;

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;

        proxy_buffering off;
        proxy_request_buffering off;

        chunked_transfer_encoding on;
    }
}
