# Generated by Django 5.2.6 on 2025-09-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='nome',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
