# Generated by Django 5.2.6 on 2025-09-24 01:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0003_alter_documento_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='conteudo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
