# Generated by Django 5.2.6 on 2025-09-24 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0004_documento_conteudo_alter_documento_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddingdocumento',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='ia.documento'),
        ),
    ]
