# Generated by Django 5.2.6 on 2025-09-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0005_alter_embeddingdocumento_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('processado', 'Processado')], default='pendente', max_length=20),
        ),
    ]
