# Generated by Django 5.1 on 2025-10-07 13:10

import ia.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0006_documento_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='embeddingdocumento',
            index=ia.indexes.BM25Index(fields=['id', 'conteudo'], key_field='id', name='bm25_index_conteudo'),
        ),
    ]
