# Generated by Django 5.1 on 2025-10-07 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0007_embeddingdocumento_bm25_index_conteudo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmbeddingDocumento',
            new_name='ChunkDocumeto',
        ),
    ]
