# Generated by Django 5.2.6 on 2025-10-08 19:24

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0008_rename_embeddingdocumento_chunkdocumeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkdocumeto',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536),
        ),
    ]
