# Generated by Django 5.2.8 on 2025-11-17 19:01

import chat.indexes
import django.core.validators
import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('arquivo', models.FileField(upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('conteudo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('processado', 'Processado')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RespostaCanonica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField()),
                ('resposta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('USUARIO', 'Usuário'), ('ASSISTENTE', 'Assistente')], max_length=20)),
                ('like', models.BooleanField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conteudo', models.TextField()),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chat.conversa')),
                ('mensagem_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='chat.mensagem')),
                ('resposta_canonica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chat.respostacanonica')),
            ],
        ),
        migrations.CreateModel(
            name='ChunkDocumeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='chat.documento')),
            ],
            options={
                'indexes': [chat.indexes.BM25Index(fields=['id', 'conteudo'], key_field='id', name='bm25_index_conteudo')],
            },
        ),
    ]
