# Generated by Django 5.2.8 on 2025-12-02 13:16

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostacanonica',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, null=True),
        ),
    ]
