# Generated by Django 5.2.8 on 2025-12-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_conversa_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversa',
            name='nome',
            field=models.CharField(default='Nova Conversa', max_length=50),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='conteudo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
