# Generated by Django 5.2.8 on 2025-12-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_conversa_nome_alter_mensagem_conteudo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagem',
            old_name='tipo_usuario',
            new_name='tipo',
        ),
    ]
