# Generated by Django 5.2.8 on 2025-12-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_tipo_usuario_mensagem_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='conteudo',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
