# Generated by Django 5.2.8 on 2025-12-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_mensagem_conteudo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagem',
            old_name='mensagem_anterior',
            new_name='mensagem_pai',
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='conteudo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
