# Generated by Django 5.2.8 on 2025-12-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_mensagem_anterior_mensagem_mensagem_pai_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagem',
            old_name='like',
            new_name='curtido',
        ),
    ]
