# Generated by Django 5.2.8 on 2025-12-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_respostacanonica_embedding'),
        ('chat', '0007_rename_like_mensagem_curtido'),
    ]

    operations = [
    ]
