# Generated by Django 5.2.8 on 2025-12-19 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_merge_20251210_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensagem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
