# Generated by Django 5.2.8 on 2026-01-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_mensagem_created_at_mensagem_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(choices=[('manual', 'Manual'), ('legislacao', 'Legislação')], default='manual', max_length=20),
        ),
    ]
