# Generated by Django 5.2.8 on 2026-01-26 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_documento_tipo_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='tipo_documento',
            new_name='tipo',
        ),
    ]
