# Generated by Django 5.2.8 on 2026-03-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_rename_tipo_documento_documento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('processado', 'Processado'), ('erro', 'Erro')], default='pendente', max_length=20),
        ),
    ]
