# Generated by Django 5.2.8 on 2026-03-18 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_add_erro_status_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='visitada_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
